name: in_app_review
description: The Flutter plugin for Google Play In-App Review.
version: 0.0.2
homepage: https://github.com/AnupKumarPanwar/in_app_review

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.anupkumarpanwar.in_app_review
        pluginClass: InAppReviewPlugin
