name: in_app_review_play_store
description: The Flutter plugin for Google Play In-App Review that lets you prompt users to submit Play Store ratings and reviews without the inconvenience of leaving your app or game.
version: 0.0.3
homepage: https://github.com/AnupKumarPanwar/in_app_review_play_store

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.anupkumarpanwar.in_app_review_play_store
        pluginClass: InAppReviewPlugin
